---
- include: fedora.yml
  when: ansible_distribution == "Fedora"

- name: Create kubernetes config directory
  file: path={{ kube_config_dir }} state=directory

- name: Create kubernetes script directory
  file: path={{ kube_script_dir }} state=directory

- name: write the global config file
  template: src=config.j2 dest={{ kube_config_dir }}/config
  notify:
    - restart daemons

- include: certs.yml
  tags:
    certs
